# Generated by Django 2.2.3 on 2019-07-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True, verbose_name='username')),
                ('contact', models.CharField(max_length=10, null=True, verbose_name='Contact number')),
                ('firstname', models.CharField(max_length=10, null=True, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=10, null=True, verbose_name='Last Name')),
                ('email', models.CharField(max_length=40, null=True, verbose_name='email')),
                ('password', models.CharField(max_length=16, verbose_name='password')),
            ],
        ),
    ]
