# Generated by Django 2.2.3 on 2019-07-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190708_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_register',
            new_name='user_registers',
        ),
    ]
