# Generated by Django 2.2.3 on 2019-07-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190708_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_registers',
            new_name='user_register',
        ),
    ]
