# Generated by Django 2.2.3 on 2019-07-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190709_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='deadline',
            field=models.CharField(max_length=30, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='money_to_be_saved',
            field=models.CharField(max_length=10, verbose_name='MoneytobeSaved'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='contact',
            field=models.CharField(max_length=15, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='firstname',
            field=models.CharField(max_length=20, null=True, verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='lastname',
            field=models.CharField(max_length=20, null=True, verbose_name='lastname'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='password',
            field=models.CharField(max_length=20, null=True, verbose_name='password'),
        ),
    ]
