# Generated by Django 2.2.3 on 2019-07-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190709_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True, verbose_name='username')),
                ('amountpaid', models.CharField(max_length=5, null=True, verbose_name='amount_to_be_paid')),
                ('tiemstamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
