# Generated by Django 2.2.3 on 2019-07-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190710_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount_to_be_paid',
            field=models.CharField(max_length=10, null=True, verbose_name='amount_to_be_paid'),
        ),
    ]
