# Generated by Django 2.2.3 on 2019-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190710_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='tiemstamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='amount_to_be_paid',
        ),
        migrations.AddField(
            model_name='transactions',
            name='amountpaid',
            field=models.CharField(max_length=10, null=True, verbose_name='amountpaid'),
        ),
    ]
